const recipes = [
  {
    title: "Salade de quinoa aux légumes grillés",
    img: "quinoa.jpg",
    description: "Une salade fraîche et saine parfaite pour l'été.",
    ingredients: [
      { name: "Quinoa", quantity: 1, unit: "tasse" },
      { name: "Poivrons rouges", quantity: 2, unit: "unités" },
      { name: "Courgettes", quantity: 2, unit: "unités" },
      { name: "Tomates cerises", quantity: 1, unit: "tasse" },
      { name: "Huile d'olive", quantity: 2, unit: "cuillères à soupe" },
      { name: "Jus de citron", quantity: 1, unit: "cuillère à soupe" },
      { name: "Sel", quantity: 1, unit: "pincée" },
      { name: "Poivre", quantity: 1, unit: "pincée" },
    ],
    tags: ["salade", "quinoa", "légumes", "grillés"],
    duration: 30,
  },
  {
    title: "Poulet rôti aux herbes",
    img: "poulet.jpg",
    description: "Un plat classique parfait pour un repas en famille.",
    ingredients: [
      { name: "Poulet entier", quantity: 1, unit: "unité" },
      { name: "Ail", quantity: 4, unit: "gousses" },
      { name: "Thym frais", quantity: 2, unit: "brins" },
      { name: "Romarin frais", quantity: 2, unit: "brins" },
      { name: "Citron", quantity: 1, unit: "unité" },
      { name: "Huile d'olive", quantity: 2, unit: "cuillères à soupe" },
      { name: "Sel", quantity: 1, unit: "cuillère à café" },
      { name: "Poivre", quantity: 1, unit: "cuillère à café" },
    ],
    tags: ["poulet", "rôti", "herbes"],
    duration: 90,
  },
  {
    title: "Pâtes à la carbonara",
    img: "carbonara.jpg",
    description: "Un plat italien crémeux et délicieux.",
    ingredients: [
      { name: "Spaghetti", quantity: 200, unit: "grammes" },
      { name: "Lardons", quantity: 150, unit: "grammes" },
      { name: "Œufs", quantity: 2, unit: "unités" },
      { name: "Parmesan râpé", quantity: 50, unit: "grammes" },
      { name: "Crème fraîche", quantity: 100, unit: "millilitres" },
      { name: "Poivre noir", quantity: 1, unit: "pincée" },
    ],
    tags: ["pâtes", "carbonara", "italien"],
    duration: 20,
  },
  {
    title: "Smoothie aux fruits frais",
    img: "smoothie.jpg",
    description: "Une boisson rafraîchissante pleine de vitamines.",
    ingredients: [
      { name: "Fraises", quantity: 1, unit: "tasse" },
      { name: "Banane", quantity: 1, unit: "unité" },
      { name: "Ananas", quantity: 1, unit: "tasse" },
      { name: "Yaourt nature", quantity: 150, unit: "grammes" },
      { name: "Miel", quantity: 1, unit: "cuillère à soupe" },
    ],
    tags: ["smoothie", "fruits", "boisson"],
    duration: 10,
  },
  {
    title: "Salade César",
    img: "cesar.jpg",
    description: "Une salade classique avec une vinaigrette crémeuse.",
    ingredients: [
      { name: "Laitue romaine", quantity: 1, unit: "tête" },
      { name: "Poulet grillé", quantity: 200, unit: "grammes" },
      { name: "Croûtons", quantity: 100, unit: "grammes" },
      { name: "Parmesan râpé", quantity: 50, unit: "grammes" },
      { name: "Sauce César", quantity: 4, unit: "cuillères à soupe" },
    ],
    tags: ["salade", "cesar", "poulet"],
    duration: 15,
  },
  {
    title: "Riz sauté aux légumes",
    img: "riz.jpg",
    description: "Un plat asiatique coloré et plein de saveurs.",
    ingredients: [
      { name: "Riz cuit", quantity: 2, unit: "tasses" },
      { name: "Carottes", quantity: 2, unit: "unités" },
      { name: "Poivrons", quantity: 2, unit: "unités" },
      { name: "Petits pois", quantity: 1, unit: "tasse" },
      { name: "Oignons", quantity: 1, unit: "unité" },
      { name: "Ail", quantity: 2, unit: "gousses" },
      { name: "Sauce soja", quantity: 2, unit: "cuillères à soupe" },
      { name: "Huile de sésame", quantity: 1, unit: "cuillère à soupe" },
      { name: "Œufs battus", quantity: 2, unit: "unités" },
    ],
    tags: ["riz", "légumes", "asiatique"],
    duration: 25,
  },
];
